version: '3.4'

services:
  api:
    image: mindekm/aspnetcore-crosscompilation:latest
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    ports:
      - "5000:8080"
